name: webf_ui_kit
description: A collection of Flutter UI components for WebF applications
version: 0.1.0-beta.1
homepage: https://openwebf.com

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webf: 
    hosted: https://dart.cloudsmith.io/openwebf/webf-enterprise/
    version: ^0.23.0-beta.3
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  easy_refresh: ^3.4.0
  dropdown_button2: ^2.3.9


  flutter_svg: ^2.0.17
  showcaseview: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Information used by the publishing tool.
publish_to: https://dart.cloudsmith.io/openwebf/webf-ui-kit/

topics:
  - webf
  - ui
  - components
  - flutter
  - widgets