name: webf_share
description: WebF Share module for sharing content, text, and images
version: 0.1.0-beta
homepage: https://openwebf.com

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webf: 
    hosted: https://dart.cloudsmith.io/openwebf/webf-enterprise/
    version: ^0.22.0
  share_plus: ^10.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

# Information used by the publishing tool.
publish_to: https://dart.cloudsmith.io/openwebf/webf-share/

topics:
  - webf
  - share
  - screenshot
  - social